
version: 2

models:
  - name: rtgs_journal_entries_clean
    description: "RTGS Journal Entries"
    columns:
      - name: accountkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
